### ISSUE TITLE
Server configuration PLS HELP

### ISSUE THREAD

**Issue by JeffreyRandom** [DonAlex0/GMDPrivateServer#1]
In email.php also all editable containing email changes (changePassword, changeUsername, lostPassword and registerGJAccount.php) and smtp (125, 132 lines), what should i put? Help pls, im new at this.

Or can you make some tutorial?

**Comment by DonAlex0** [comment]
Wait a second, I better create an option to disable real email usage.

**Comment by JeffreyRandom** [comment]
Its says this when enter in the website: Notice
: Undefined variable: browseActive in
/storage/ssd1/665/5737665/public_html/dashboard/incl/dashboardLib.php on line 110
Everything else it's ok,

If it's any way to not show php errors tell me pls.
Also, if at any time you have free time or something, can you help to activate email.php?

Ty, btw :)

**Comment by JeffreyRandom** [comment]
Also, this in changePassword.php:
Notice: Undefined index: userName in /storage/ssd1/665/5737665/public_html/dashboard/account/changePassword.php on line 79

Notice: Undefined index: oldpassword in /storage/ssd1/665/5737665/public_html/dashboard/account/changePassword.php on line 80

Notice: Undefined index: newpassword in /storage/ssd1/665/5737665/public_html/dashboard/account/changePassword.php on line 81

And this on changeUsername:

Notice: Undefined index: userName in /storage/ssd1/665/5737665/public_html/dashboard/account/changeUsername.php on line 79

Notice: Undefined index: newusr in /storage/ssd1/665/5737665/public_html/dashboard/account/changeUsername.php on line 81

Notice: Undefined index: password in /storage/ssd1/665/5737665/public_html/dashboard/account/changeUsername.php on line 83

Also, i had an old gdps, want to reupload some levels from it... how to?
This is my old url: https://gmdsjeff.000webhostapp.com/
New one: https://jefgdps2.000webhostapp.com/

And, how to change the word "Dashboard" or i can't?

Everything else, (i don't see anything else wrong) its fine. Ty again :)

**Comment by DonAlex0** [comment]
Keep an eye about updates, I'll fix it in leas than 24 hours

**Comment by JeffreyRandom** [comment]
I haven't told you if disable email works, well... it works xD
