### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ItzLennyFace** [DonAlex0/GMDPrivateServer#10]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the FAQs for common solutions: http://robtopgames.pe.hu/faq
    * Checked that your issue is not already filed: https://github.com/DonAlex0/GMDPrivateServer/issues?utf8=✓&q=

### Description

https://ibb.co/dy1Yio

### Steps to Reproduce

Idk...

**Expected behavior:** ...

**Actual behavior:** ...

**Reproduces how often:** ...

### Versions

This is suggestion, not issue.

### Additional Information

None.

**Comment by DonAlex0** [comment]
And what do you really suggest me?

**Comment by ItzLennyFace** [comment]
Elder Mods & Mods should have permission to delete comments

**Comment by DonAlex0** [comment]
Elder Mods have permission, it's already made in GD code, just set actionRequestMod to 2 for Elder Mods

**Comment by ItzLennyFace** [comment]
Oh ok. Thx for info.
