### ISSUE TITLE
How i setting a email?

### ISSUE THREAD

**Issue by Gibsix** [DonAlex0/GMDPrivateServer#12]
How i setting a email?

**Comment by DonAlex0** [comment]
Everything's explained in readme file, you need an email account, for example I use https://www.migadu.com. If you use a Gmail account the SMTP server is smtp.gmail.com

**Comment by Gibsix** [comment]
> Everything's explained in readme file, you need an email account, for example I use https://www.migadu.com. If you use a Gmail account the SMTP server is smtp.gmail.com

Thank you! And again. How to get email body?

**Comment by EliezerYT** [comment]
lel

**Comment by WOSHIZHAZHA120** [comment]
#14
