### ISSUE TITLE
How to setting email?

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [DonAlex0/GMDPrivateServer#14]
I use www.migadu.com but i don't know how to setting....
Always Something went wrong......

**Comment by DonAlex0** [comment]
Send screenshot of email.php and smtp.php

**Comment by WOSHIZHAZHA120** [comment]
http://s.geometrydashchinese.com/WOSHIZHAZHA120/image/1.png
http://s.geometrydashchinese.com/WOSHIZHAZHA120/image/2.png
http://s.geometrydashchinese.com/WOSHIZHAZHA120/image/3.png
Sorry for language,
It's Chinese.
@DonAlex0

**Comment by WOSHIZHAZHA120** [comment]
Email service is normal.
I Can use this email send some email

**Comment by DonAlex0** [comment]
File not found in all three images

**Comment by WOSHIZHAZHA120** [comment]
Sorry,now is worked. @DonAlex0

**Comment by WOSHIZHAZHA120** [comment]
And I change localhost to smtp.migadu.com
