### ISSUE TITLE
How to change demon difficulty?

### ISSUE THREAD

**Issue by JeffreyRandom** [DonAlex0/GMDPrivateServer#2]
Well, it's simple. How I make any demon to specific difficulty? Like Easy Demon or Insane Demon. Command? I can't? ty :)

**Comment by JeffreyRandom** [comment]
I mean, just change demon difficulty to Easy  demon by now.

**Comment by DonAlex0** [comment]
Use the Demon button at the right side of the level

**Comment by JeffreyRandom** [comment]
Nope, it doesn't work, nothing happens.

**Comment by DonAlex0** [comment]
Yes, I am still here

**Comment by JeffreyRandom** [comment]
I still can't change demon

**Comment by DonAlex0** [comment]
I'm still working on this issues

**Comment by JeffreyRandom** [comment]
Uhmm, ok. I will wait patiently :)

**Comment by JeffreyRandom** [comment]
Just to know, can I switch your rateGJDemon.php by the rateGJDemon.php by Cvolton?

**Comment by DonAlex0** [comment]
You should, I'm bussy with exams so you can expect me to upload a bug fix the 20th

**Comment by JeffreyRandom** [comment]
Mmm, ok thanks m8.
Btw, in roles i just changed the requestMod option at 2, and works perfectly with yours, only thing is when people with normal mod (requestMod = 1), there's a table named "demondiffsuggesions" should add the mod's action (suggestion) but it does not add nothing. But for now, changing it to 2 (rhyme lol) works perfectly without any commands, also while rating. Your gdps files help me a lot, thank you for not ignoring me in the problems I had had.
I have not write something that long, lol.
