### ISSUE TITLE
Gauntlets bug

### ISSUE THREAD

**Issue by JeffreyRandom** [DonAlex0/GMDPrivateServer#5]
When I beat a level from a gauntlet can't go to next one. Also when enter in first gauntlet level, menu background level usually should be like black while playing on gauntlets. But it appears like a normal level (blue background)

**Comment by DonAlex0** [comment]
That's a GD bug, I think

**Comment by DonAlex0** [comment]
I'll take a look at it anyway

**Comment by JeffreyRandom** [comment]
Ok, that's the last issue i have for now, i think.
Also I tried with the .exe without changing the links at HxD, and looks everything is fine. So i think the problem is on some file changed from cvolton's files, i really don't know. Thanks for respond anyways :)
