### ISSUE TITLE
Levels and comment history bug

### ISSUE THREAD

**Issue by JeffreyRandom** [DonAlex0/GMDPrivateServer#6]
When I go to a profile, and click on levels, doesn't appear any level (obviosly this user have levels uploaded) also when I click on the history comments button doesn't appear any comment too. I tried with my account and with another, but doesn't show any history comment. Ty for reading :)

**Comment by DonAlex0** [comment]
Seems I have a lot of work to do, all of these bugs will be fixed within the next two weeks, thanks you for supporting the development of the project :)

**Comment by DonAlex0** [comment]
By the way, I highly recommend you when making an issue to use the issue template created for the project.

**Comment by JeffreyRandom** [comment]
Ok, thank you again for answer. :)
