### ISSUE TITLE
Questions (now its valid lol)

### ISSUE THREAD

**Issue by ItzLennyFace** [DonAlex0/GMDPrivateServer#9]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the FAQs for common solutions: http://robtopgames.pe.hu/faq
    * Checked that your issue is not already filed: https://github.com/DonAlex0/GMDPrivateServer/issues?utf8=✓&q=

### Description

1. How to replace d/m/Y G:i with "1 day ago, 1 minute ago" ?
2. How to make gauntlets order by older ID to newer ID?

### Steps to Reproduce

I dont know

**Expected behavior:** -
**Actual behavior:** -
**Reproduces how often:** -

### Versions

Android 7.1.2

### Additional Information

none

**Comment by DonAlex0** [comment]
That are questions you can search on Google or answer yourself seeing the server files.

**Comment by ItzLennyFace** [comment]
Ok, but can u answer to 2th question?
